'use client';
import { FormEvent,useState } from 'react';
import Link from 'next/link';
import { call } from '@/lib/firebase';
import { useRows } from '@/lib/hooks';
import { Row } from '@/lib/types';
import { errorMessage,money } from '@/lib/utils';
import { Button,Empty,Loading,Modal,Notice,PageHeading } from '../ui';
import { cents,TrainingType,typeLabel,types } from './offer-shared';

export function AdminOfferTemplates(){const data=useRows('offerTemplates'),[selected,setSelected]=useState<Row|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState('');
  async function deactivate(row:Row){if(!window.confirm(`Deactivate "${row.title}"? Existing sessions will remain unchanged.`))return;setBusy(row.id);setError('');try{await call('deleteOfferTemplate',{templateId:row.id});}catch(e){setError(errorMessage(e));}finally{setBusy('');}}
  return <><PageHeading title="Session templates." eyebrow="Sessions"/><div className="admin-toolbar"><Button onClick={()=>setSelected({id:''})}>Create template</Button><Link className="button secondary" href="/admin/offers">Back to sessions</Link></div>{(error||data.error)&&<Notice error>{error||data.error}</Notice>}{data.loading?<Loading/>:data.rows.length?<div className="stack">{data.rows.map(row=><article className="card row spread" key={row.id}><div><h3>{row.title}</h3><p className="muted" style={{margin:0}}>{typeLabel(row.trainingType)} · {money(row.defaultPriceCents||0)} · {row.defaultCapacity} seats · {row.isActive?'Active':'Inactive'}</p></div><div className="row"><Button className="secondary small" onClick={()=>setSelected(row)}>Edit</Button>{row.isActive&&<Button className="secondary small" disabled={busy===row.id} onClick={()=>deactivate(row)}>Deactivate</Button>}</div></article>)}</div>:<Empty>No templates yet.</Empty>}{selected&&<TemplateEditor key={selected.id||'new'} row={selected} onClose={()=>setSelected(null)}/>}</>;
}
function TemplateEditor({row,onClose}:{row:Row;onClose:()=>void}){
  const [type,setType]=useState<TrainingType>(row.trainingType||'private'),[capacity,setCapacity]=useState<number>(row.defaultCapacity||1),[busy,setBusy]=useState(false),[error,setError]=useState('');
  function changeType(next:TrainingType){setType(next);setCapacity(next==='private'?1:next==='duo'?2:Math.max(3,capacity));}
  async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();const values=Object.fromEntries(new FormData(e.currentTarget)) as Record<string,string>;setBusy(true);setError('');try{await call('saveOfferTemplate',{...(row.id?{templateId:row.id}:{}),title:values.title.trim(),description:values.description.trim(),trainingType:type,defaultPriceCents:cents(values.price),defaultCapacity:capacity,durationMinutes:Number(values.durationMinutes),ageGroup:values.ageGroup.trim(),imageUrl:values.imageUrl.trim()||null,isActive:values.isActive==='on'});onClose();}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
  return <Modal title={row.id?'Edit template':'Create template'} onClose={onClose}><form className="stack" onSubmit={save}><label className="field">Title<input name="title" maxLength={80} required defaultValue={row.title||''}/></label><label className="field">Description<textarea name="description" maxLength={1000} defaultValue={row.description||''}/></label><div className="field-grid"><label className="field">Type<select value={type} onChange={e=>changeType(e.target.value as TrainingType)}>{types.map(item=><option key={item} value={item}>{typeLabel(item)}</option>)}</select></label><label className="field">Seats<input type="number" min={type==='group'?3:capacity} max={type==='group'?50:capacity} readOnly={type!=='group'} value={capacity} onChange={e=>setCapacity(Number(e.target.value))}/></label></div><div className="field-grid"><label className="field">Default price (USD)<input name="price" required defaultValue={row.defaultPriceCents?String(row.defaultPriceCents/100):''}/></label><label className="field">Duration (minutes)<input name="durationMinutes" type="number" min={15} max={240} required defaultValue={row.durationMinutes||60}/></label></div><label className="field">Age group<input name="ageGroup" maxLength={40} defaultValue={row.ageGroup||''}/></label><label className="field">Default image URL (optional)<input name="imageUrl" type="url" defaultValue={row.imageUrl||''}/></label><label className="check-field"><input name="isActive" type="checkbox" defaultChecked={row.isActive!==false}/>Active</label>{error&&<Notice error>{error}</Notice>}<Button busy={busy}>Save template</Button></form></Modal>;
}
