'use client';
import { useState } from 'react';
import { where } from 'firebase/firestore';
import { call } from '@/lib/firebase';
import { useRows, useDocument } from '@/lib/hooks';
import { Row } from '@/lib/types';
import { dateLabel,timeLabel,asDate,money,errorMessage } from '@/lib/utils';
import { Button,Notice,PageHeading,Loading,Modal,Empty } from '../ui';
import { usePaged,Pagination,Status } from './data';
import { PaymentSetup } from './payment-setup';
import { ExportDialog } from './bookings';
export function AdminPayments(){const [status,setStatus]=useState(''),[method,setMethod]=useState(''),[error,setError]=useState(''),[record,setRecord]=useState(false),[exporting,setExporting]=useState(false),[busy,setBusy]=useState(''),[delivery,setDelivery]=useState<Row|null>(null);const data=usePaged('payments','createdAt',[...(status?[where('status','==',status)]:[]),...(method?[where('paymentMethod','==',method)]:[])],`${status}:${method}`);return <><PageHeading title="Payments."/><PaymentSetup/><div className="admin-toolbar"><Button onClick={()=>setRecord(true)}>Record Cash / Manual Payment</Button><label className="field">Status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All</option>{['completed','pending','failed','refund_pending','refunded'].map(s=><option key={s}>{s}</option>)}</select></label><label className="field">Method<select value={method} onChange={e=>setMethod(e.target.value)}><option value="">All</option>{['stripe','cash','manual'].map(s=><option key={s}>{s}</option>)}</select></label><Button className="secondary" onClick={()=>setExporting(true)}>Export CSV</Button></div>{(error||data.error)&&<Notice error>{error||data.error}</Notice>}{data.loading?<Loading/>:data.rows.length?<div className="table-wrap"><table><thead><tr><th>Date</th><th>Member</th><th>Item</th><th>Delivery</th><th>Amount</th><th>Method</th><th>Status</th><th>Action</th></tr></thead><tbody>{data.rows.map(p=><tr key={p.id}><td>{dateLabel(p.createdAt)} · {timeLabel(p.createdAt)}</td><td>{p.userId}</td><td>{p.productName?`${p.productName}${p.size?` · Size ${p.size}`:''} (store)`:'Membership'}</td><td>{p.estimatedDeliveryDate?dateLabel(p.estimatedDeliveryDate):'—'}</td><td>{money(p.amount)}</td><td>{p.paymentMethod}</td><td><Status row={p}/></td><td className="row">{p.productName&&<Button className="text small" onClick={()=>setDelivery(p)}>Buyer & Delivery</Button>}{['completed','refund_pending'].includes(p.status)&&<Button className="secondary small" disabled={busy===p.id} onClick={async()=>{if(!window.confirm(p.productName?`Refund ${money(p.amount)} for ${p.productName}?`:`Refund ${money(p.amount)}? Unused session credits will be removed.`))return;setBusy(p.id);try{await call('createRefund',{paymentId:p.id});}catch(e){setError(errorMessage(e));}finally{setBusy('');}}}>{p.status==='refund_pending'?'Retry refund':'Refund'}</Button>}</td></tr>)}</tbody></table></div>:<Empty>No matching payments.</Empty>}<Pagination data={data}/>{record&&<ManualPayment onClose={()=>setRecord(false)}/>} {exporting&&<ExportDialog collection="payments" onClose={()=>setExporting(false)}/>}{delivery&&<BuyerDelivery payment={delivery} onClose={()=>setDelivery(null)}/>}</>;}
function BuyerDelivery({payment,onClose}:{payment:Row;onClose:()=>void}){const buyer=useDocument(`users/${payment.userId}`);const [busy,setBusy]=useState(false),[error,setError]=useState('');const canSchedule=payment.status==='completed';return <Modal title="Buyer & Delivery" onClose={onClose}><div className="stack"><p><strong>{payment.productName?`${payment.productName}${payment.size?` (Size ${payment.size})`:''}`:'Membership'}</strong> · {money(payment.amount)}</p>{buyer===null?<Loading/>:<div className="card" style={{padding:12}}><p style={{margin:0,fontWeight:600}}>{buyer.fullName} {buyer.lastName||''}</p><p className="muted" style={{margin:'4px 0',fontSize:13}}>{buyer.phone||'No phone on file'} · {buyer.email||'—'}</p><p style={{margin:0,fontSize:13}}>{buyer.address?`${buyer.address}${buyer.zipCode?`, ${buyer.zipCode}`:''}`:'No address on file'}</p></div>}{canSchedule?<form className="stack" onSubmit={async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget)) as Record<string,string>;setBusy(true);setError('');try{await call('setOrderDelivery',{paymentId:payment.id,estimatedDeliveryDate:new Date(f.date).toISOString(),note:f.note||''});onClose();}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}}><label className="field">Expected delivery / pickup date<input type="date" name="date" required defaultValue={payment.estimatedDeliveryDate?asDate(payment.estimatedDeliveryDate).toISOString().slice(0,10):''}/></label><label className="field">Note for the buyer (optional)<input name="note" maxLength={300} defaultValue={payment.deliveryNote||''} placeholder="e.g. Ships via USPS, or ready for pickup at the front desk"/></label>{error&&<Notice error>{error}</Notice>}<Button busy={busy}>Save Delivery Date</Button></form>:<p className="muted" style={{fontSize:13}}>Delivery scheduling is only available for paid store orders.</p>}</div></Modal>;}
function ManualPayment({onClose}:{onClose:()=>void}){const plans=useRows('membershipPlans',[where('isActive','==',true)]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[requestId]=useState(()=>crypto.randomUUID());return <Modal title="Record Payment" onClose={onClose}><form className="stack" onSubmit={async e=>{e.preventDefault();setBusy(true);try{await call('recordManualPayment',{...Object.fromEntries(new FormData(e.currentTarget)),requestId});onClose();}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}}><label className="field">Member ID<input name="userId" required/></label><label className="field">Plan<select name="planId" required>{plans.rows.map(p=><option key={p.id} value={p.id}>{p.name} · {money(p.price)}</option>)}</select></label><label className="field">Method<select name="method"><option value="cash">Cash</option><option value="manual">Manual</option></select></label><label className="field">Reference or note<input name="note" maxLength={500}/></label><p className="muted" style={{fontSize:12}}>Confirm the money has been received. The selected plan’s session credits will be added immediately.</p>{error&&<Notice error>{error}</Notice>}<Button busy={busy}>Record Payment</Button></form></Modal>;}
