// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEL-wn5kpLq2XkARZ-2Zq3wcvFnTQuqs0',
    appId: '1:772438105367:ios:80fe0d32bb600ce7a66b52',
    messagingSenderId: '772438105367',
    projectId: 'box-jbb',
    storageBucket: 'box-jbb.firebasestorage.app',
    androidClientId: '772438105367-nreb62mhfm2bfu7edis68hb4tsmhrvsv.apps.googleusercontent.com',
    iosClientId: '772438105367-1gt9qnqsehm7vpr51tfsvt91b549qcl6.apps.googleusercontent.com',
    iosBundleId: 'com.box.sharif.juniorBoyBoxing',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbRtbKQKE_Lle6SYd3OeQcehFVnbte-uo',
    appId: '1:772438105367:android:33effdddc1c2550aa66b52',
    messagingSenderId: '772438105367',
    projectId: 'box-jbb',
    storageBucket: 'box-jbb.firebasestorage.app',
  );
}
