'use client';
import { FormEvent, ReactNode, useState } from 'react';
import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { doc, orderBy, serverTimestamp, updateDoc, where, limit } from 'firebase/firestore';
import { ref, uploadBytes, getDownloadURL } from 'firebase/storage';
import { sendPasswordResetEmail, verifyBeforeUpdateEmail } from 'firebase/auth';
import { db, storage, auth, call } from '@/lib/firebase';
import { useRows, useDocument } from '@/lib/hooks';
import { asDate, dateLabel, timeLabel, money, errorMessage, composeAddress } from '@/lib/utils';
import { Row } from '@/lib/types';
import { useAuth } from './providers';
import { AddressFields } from './address-fields';
import { ActionLink, Button, Empty, Loading, Notice, PageHeading, Modal } from './ui';
import { Schedule } from './schedule';

export function MemberGuard({children}:{children:ReactNode}){const {user,profile,loading,error}=useAuth();if(loading)return <Loading/>;if(!user)return <div className="container page-wrap"><PageHeading title="Your training, all in one place."/><ActionLink href="/signin">Sign In</ActionLink></div>;if(error)return <Notice error>{error}</Notice>;if(profile?.isActive===false)return <Notice error>Your account is inactive. Contact the gym.</Notice>;return <>{children}</>;}
export function MemberShell({children}:{children:ReactNode}){const path=usePathname();return <MemberGuard><div className="container page-wrap"><nav className="portal-nav" aria-label="Member navigation">{[['Dashboard','/dashboard'],['Book a Class','/book'],['My Bookings','/bookings'],['Membership','/membership'],['Payments','/payments'],['Waiver','/waiver'],['Notifications','/notifications'],['Settings','/settings']].map(([title,href])=><Link key={href} href={href} className={path===href?'active':''}>{title}</Link>)}</nav>{children}</div></MemberGuard>;}
export function DashboardPage(){const {user,profile}=useAuth();const {rows,error,loading}=useRows(user?'bookings':null,[where('userId','==',user?.uid||''),orderBy('date','desc'),limit(100)],user?.uid);const next=rows.filter(b=>b.status==='confirmed'&&asDate(b.date)>new Date()).sort((a,b)=>+asDate(a.date)-+asDate(b.date))[0];const {rows:products}=useRows('products',[where('isActive','==',true)]);const featured=products.find(p=>p.isFeatured===true);return <MemberShell><PageHeading eyebrow="Your member portal" title={`Welcome back, ${profile?.fullName?.split(' ')[0]||'Champion'}.`}>Keep training. Keep improving.</PageHeading>{featured&&<div className="card row spread" style={{borderColor:'var(--red)',margin:'24px 0'}}><div className="row">{featured.imageUrl&&<img src={featured.imageUrl} alt="" style={{width:56,height:56,objectFit:'cover',borderRadius:8}}/>}<div><p className="eyebrow">From the gym store</p><h3 style={{margin:0}}>{featured.name}</h3><p className="muted" style={{margin:0}}>{featured.priceLabel}</p></div></div><ActionLink href="/store">Shop Now</ActionLink></div>}<div className="stats-grid"><div className="card stat"><span>Sessions remaining</span><strong>{profile?.sessionsRemaining??0}</strong></div><div className="card stat"><span>Reserved sessions</span><strong>{profile?.sessionsReserved??0}</strong></div><div className="card stat"><span>Available to book</span><strong>{Math.max(0,(profile?.sessionsRemaining??0)-(profile?.sessionsReserved??0))}</strong></div><div className="card stat"><span>Member since</span><strong style={{fontSize:22}}>{profile?.memberSince?dateLabel(profile.memberSince):'Today'}</strong></div></div>{error&&<Notice error>{error}</Notice>}{loading?<Loading/>:next?<div className="card row spread" style={{borderColor:'var(--red)',margin:'24px 0'}}><div><p className="eyebrow">Your next session</p><h2 style={{fontSize:30}}>{next.className}</h2><p className="muted">{dateLabel(next.date)} · {timeLabel(next.date)} PT</p></div><ActionLink href="/bookings">View Booking</ActionLink></div>:<Empty>No upcoming sessions. Make room for your next round.</Empty>}<div className="row"><ActionLink href="/book">Book a Class</ActionLink><ActionLink href="/membership" secondary>Manage Membership</ActionLink>{profile?.role==='admin'&&<ActionLink href="/admin" secondary>Admin Dashboard</ActionLink>}</div><h2 style={{fontSize:28,marginTop:42}}>Recent bookings</h2><BookingTable rows={rows.slice(0,5)}/></MemberShell>;}
function BookingTable({rows,onCancel}:{rows:Row[];onCancel?:(row:Row)=>void}){return rows.length?<div className="table-wrap"><table><thead><tr><th>Class</th><th>Category</th><th>Date & time</th><th>Status</th>{onCancel&&<th>Manage</th>}</tr></thead><tbody>{rows.map(b=><tr key={b.id}><td>{b.className}</td><td>{b.category?<span className="badge badge-red">{b.category}</span>:'—'}</td><td>{dateLabel(b.date)} · {timeLabel(b.date)}</td><td><span className={`status ${b.status}`}>{b.status}</span></td>{onCancel&&<td>{b.status==='confirmed'&&asDate(b.date)>new Date()&&<button className="button text small" onClick={()=>onCancel(b)}>Cancel</button>}</td>}</tr>)}</tbody></table></div>:<Empty>No bookings to show.</Empty>;}
export function BookingsPage(){const {user}=useAuth(),[tab,setTab]=useState('upcoming'),[selected,setSelected]=useState<Row|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');const config=useDocument('gymSettings/config');const data=useRows(user?'bookings':null,[where('userId','==',user?.uid||''),orderBy('date','desc'),limit(200)],user?.uid);const rows=data.rows.filter(b=>tab==='cancelled'?b.status==='cancelled':tab==='upcoming'?b.status==='confirmed'&&asDate(b.date)>new Date():b.status!=='cancelled'&&(asDate(b.date)<=new Date()||b.status!=='confirmed'));async function cancel(){if(!selected)return;setBusy(true);try{await call('cancelBooking',{bookingId:selected.id,reason:'Cancelled by member'});setSelected(null);}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}const permitted=selected&&+asDate(selected.date)-Date.now()>=(config?.cancellationPolicyHours??24)*3600000;return <MemberShell><PageHeading title="My Bookings."/><div className="tabs">{['upcoming','past','cancelled'].map(t=><button key={t} className={tab===t?'active':''} onClick={()=>setTab(t)}>{t[0].toUpperCase()+t.slice(1)}</button>)}</div>{data.error&&<Notice error>{data.error}</Notice>}{data.loading?<Loading/>:<BookingTable rows={rows} onCancel={row=>{setSelected(row);setError('');}}/>}{selected&&<Modal title="Cancel booking?" onClose={()=>setSelected(null)}><p>{selected.className} · {dateLabel(selected.date)}</p>{error&&<Notice error>{error}</Notice>}{permitted?<><p className="muted">Your reserved session credit will be released.</p><Button busy={busy} onClick={cancel}>Cancel Booking</Button></>:<><Notice>The cancellation window has closed. Contact the gym for help.</Notice><ActionLink href="/contact">Contact the gym</ActionLink></>}</Modal>}</MemberShell>;}
export function BookPage(){return <MemberShell><PageHeading title="Your next round.">Choose a class and reserve your place.</PageHeading><Schedule/></MemberShell>;}
export function MembershipPage(){const {user,profile}=useAuth();const data=useRows(user?'payments':null,[where('userId','==',user?.uid||''),orderBy('createdAt','desc'),limit(100)],user?.uid);return <MemberShell><PageHeading title="Your Membership."/><div className="card row spread"><div><p className="eyebrow">Training credits</p><h2 style={{fontSize:32}}>{profile?.sessionsRemaining??0} sessions remaining</h2><p className="muted">{profile?.sessionsReserved??0} reserved for upcoming classes</p></div><ActionLink href="/pricing">Add Session Credits</ActionLink></div><h2 style={{fontSize:28,marginTop:38}}>Payment history</h2>{data.error&&<Notice error>{data.error}</Notice>}{data.loading?<Loading/>:data.rows.length?<div className="table-wrap"><table><thead><tr><th>Date</th><th>Item</th><th>Amount</th><th>Method</th><th>Status</th><th>Delivery</th><th>Receipt</th></tr></thead><tbody>{data.rows.map(p=><tr key={p.id}><td>{dateLabel(p.createdAt)} · {timeLabel(p.createdAt)}</td><td>{p.productName?`${p.productName}${p.size?` · Size ${p.size}`:''} (store)`:'Membership'}</td><td>{money(p.amount)}</td><td>{p.paymentMethod}</td><td><span className={`status ${p.status}`}>{p.status}</span></td><td>{p.estimatedDeliveryDate?dateLabel(p.estimatedDeliveryDate):'—'}</td><td>{p.receiptUrl&&<a href={p.receiptUrl} target="_blank" rel="noreferrer">View receipt ↗</a>}</td></tr>)}</tbody></table></div>:<Empty>No payments yet.</Empty>}</MemberShell>;}
export function SettingsPage(){const {user,profile,logout}=useAuth(),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[avatarUrl,setAvatarUrl]=useState(profile?.avatarUrl||'');async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!user)return;const form=Object.fromEntries(new FormData(e.currentTarget)) as Record<string,string>;setBusy(true);setError('');try{await updateDoc(doc(db,'users',user.uid),{fullName:form.fullName,phone:form.phone,address:composeAddress(form),childName:form.childName,childAge:Number(form.childAge),avatarUrl,notificationPreferences:{push:form.push==='on',email:form.emailNotifications==='on'},updatedAt:serverTimestamp()});if(form.email!==user.email){await verifyBeforeUpdateEmail(user,form.email);setMessage('Profile saved. Verify your new email to complete the change.');}else setMessage('Profile saved.');}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}async function avatar(file:File|undefined){if(!file||!user)return;if(file.size>=5*1024*1024||!['image/jpeg','image/png','image/webp'].includes(file.type)){setError('Choose a JPG, PNG or WebP smaller than 5 MB.');return;}setBusy(true);setError('');try{const target=ref(storage,`avatars/${user.uid}/profile`);await uploadBytes(target,file,{contentType:file.type});const url=await getDownloadURL(target);setAvatarUrl(url);await updateDoc(doc(db,'users',user.uid),{avatarUrl:url,updatedAt:serverTimestamp()});setMessage('Profile photo updated.');}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}return <MemberShell><PageHeading title="Profile Settings."/>{profile&&<form className="card stack" style={{maxWidth:750}} onSubmit={save}>
  <h3 style={{margin:0}}>Profile photo</h3>
  <div className="row" style={{alignItems:'center',gap:16}}>{avatarUrl&&<img className="avatar" src={avatarUrl} alt="Your profile" style={{width:64,height:64,borderRadius:'50%',objectFit:'cover'}}/>}<label className="field" style={{flex:1}}>Change photo<input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={e=>avatar(e.target.files?.[0])}/></label></div>
  <h3 style={{margin:0}}>Your name</h3>
  <label className="field">Full name<input name="fullName" required maxLength={100} defaultValue={profile.fullName}/></label>
  <h3 style={{margin:0}}>Contact & participant</h3>
  <div className="field-grid">{[['email','Email','email'],['phone','Phone','tel'],['childName','Participant name (yourself or child)','text'],['childAge','Participant age','number']].map(([name,label,type])=><label className="field" key={name}>{label}<input name={name} type={type} required defaultValue={profile[name]} min={type==='number'?1:undefined} max={type==='number'?120:undefined}/></label>)}</div>
  <AddressFields defaultStreet={profile.address||''}/>
  <label className="check-field"><input type="checkbox" name="push" defaultChecked={profile.notificationPreferences?.push!==false}/>Push notifications</label><label className="check-field"><input type="checkbox" name="emailNotifications" defaultChecked={profile.notificationPreferences?.email!==false}/>Email notifications</label>{error&&<Notice error>{error}</Notice>}{message&&<Notice>{message}</Notice>}<div className="row"><Button busy={busy}>Save Changes</Button><Button type="button" className="secondary" onClick={async()=>{try{await sendPasswordResetEmail(auth,user!.email!);setMessage('Password reset email sent.');}catch(e){setError(errorMessage(e));}}}>Change Password</Button><Button type="button" className="text" onClick={()=>logout().catch(e=>setError(errorMessage(e)))}>Sign Out</Button></div></form>}</MemberShell>;}
export function NotificationsPage(){const {user}=useAuth(),[error,setError]=useState('');const data=useRows(user?'notifications':null,[where('userId','==',user?.uid||''),orderBy('createdAt','desc'),limit(100)],user?.uid);return <MemberShell><PageHeading title="Notifications."/>{(error||data.error)&&<Notice error>{error||data.error}</Notice>}{data.loading?<Loading/>:data.rows.length?<div className="stack">{data.rows.map(n=><article className="card" key={n.id} style={{borderColor:n.isRead?undefined:'var(--red)'}}><h3>{n.title}</h3><p className="muted">{n.body}</p>{!n.isRead&&<Button className="text small" onClick={async()=>{try{await updateDoc(doc(db,'notifications',n.id),{isRead:true});}catch(e){setError(errorMessage(e));}}}>Mark as read</Button>}</article>)}</div>:<Empty>You’re all caught up.</Empty>}</MemberShell>;}
