'use client';
import { FormEvent, ReactNode, useState } from 'react';
import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { doc, orderBy, serverTimestamp, updateDoc, where, limit } from 'firebase/firestore';
import { ref, uploadBytes, getDownloadURL } from 'firebase/storage';
import { sendPasswordResetEmail } from 'firebase/auth';
import { db, storage, auth, call } from '@/lib/firebase';
import { useRows, useDocument } from '@/lib/hooks';
import { asDate, dateLabel, timeLabel, money, errorMessage, composeAddress, paymentMethodLabel } from '@/lib/utils';
import { Row } from '@/lib/types';
import { isStaff } from '@/lib/permissions';
import { useAuth } from './providers';
import { AddressFields } from './address-fields';
import { ActionLink, Button, Empty, Loading, Notice, PageHeading, Modal } from './ui';
import { features } from '@/lib/features';
import { AuthModal } from './auth-modal';

export function MemberGuard({children}:{children:ReactNode}){const {user,profile,loading,error}=useAuth(),[showAuth,setShowAuth]=useState(false);if(loading)return <Loading/>;if(!user)return <div className="container page-wrap"><PageHeading title="Sign in to continue."/><Button onClick={()=>setShowAuth(true)}>Sign in</Button>{showAuth&&<AuthModal onClose={()=>setShowAuth(false)} onSignedIn={()=>setShowAuth(false)}/>}</div>;if(error)return <Notice error>{error}</Notice>;if(profile?.isActive===false)return <Notice error>Your account is inactive. Contact the gym.</Notice>;return <>{children}</>;}
export function MemberShell({children}:{children:ReactNode}){return <MemberGuard><div className="container page-wrap">{children}</div></MemberGuard>;}
export function DashboardPage(){const {user,profile}=useAuth(),[tab,setTab]=useState<'schedule'|'settings'>('schedule');const data=useRows(user?'bookings':null,[where('userId','==',user?.uid||''),orderBy('date','desc'),limit(100)],user?.uid);const upcoming=data.rows.filter(b=>b.status==='confirmed'&&asDate(b.date)>new Date()).sort((a,b)=>+asDate(a.date)-+asDate(b.date));return <MemberShell><PageHeading title="Account"/><div className="tabs account-tabs" role="tablist" aria-label="Account sections"><button role="tab" aria-selected={tab==='schedule'} className={tab==='schedule'?'active':''} onClick={()=>setTab('schedule')}>My schedule</button><button role="tab" aria-selected={tab==='settings'} className={tab==='settings'?'active':''} onClick={()=>setTab('settings')}>Settings</button></div><div className="account-tab" role="tabpanel">{tab==='schedule'?<><div className="row spread account-actions"><h2>My schedule</h2><ActionLink href="/offers">Book a session</ActionLink></div>{data.error&&<Notice error>{data.error}</Notice>}{data.loading?<Loading/>:<BookingTable rows={upcoming}/>}</>:<><SettingsPage embedded/><p className="account-secondary"><Link href="/payments">Payment history</Link></p>{isStaff(profile)&&<p className="account-secondary"><Link href="/admin">Admin dashboard</Link></p>}</>}</div></MemberShell>;}
function BookingTable({rows,onCancel}:{rows:Row[];onCancel?:(row:Row)=>void}){return rows.length?<div className="table-wrap"><table><thead><tr><th>Class</th><th>Category</th><th>Date & time</th><th>Status</th>{onCancel&&<th>Manage</th>}</tr></thead><tbody>{rows.map(b=><tr key={b.id}><td>{b.className}</td><td>{b.category?<span className="badge badge-red">{b.category}</span>:'—'}</td><td>{dateLabel(b.date)} · {timeLabel(b.date)}</td><td><span className={`status ${b.status}`}>{b.status}</span></td>{onCancel&&<td>{b.status==='confirmed'&&asDate(b.date)>new Date()&&<button className="button text small" onClick={()=>onCancel(b)}>Cancel</button>}</td>}</tr>)}</tbody></table></div>:<Empty>No bookings to show.</Empty>;}
export function BookingsPage(){const {user}=useAuth(),[tab,setTab]=useState('upcoming'),[selected,setSelected]=useState<Row|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');const config=useDocument('gymSettings/config');const data=useRows(user?'bookings':null,[where('userId','==',user?.uid||''),orderBy('date','desc'),limit(200)],user?.uid);const rows=data.rows.filter(b=>tab==='cancelled'?b.status==='cancelled':tab==='upcoming'?b.status==='confirmed'&&asDate(b.date)>new Date():b.status!=='cancelled'&&(asDate(b.date)<=new Date()||b.status!=='confirmed'));async function cancel(){if(!selected)return;setBusy(true);try{await call('cancelBooking',{bookingId:selected.id,reason:'Cancelled by member'});setSelected(null);}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}const permitted=selected&&+asDate(selected.date)-Date.now()>=(config?.cancellationPolicyHours??24)*3600000;return <MemberShell><PageHeading title="My Bookings."/><div className="tabs">{['upcoming','past','cancelled'].map(t=><button key={t} className={tab===t?'active':''} onClick={()=>setTab(t)}>{t[0].toUpperCase()+t.slice(1)}</button>)}</div>{data.error&&<Notice error>{data.error}</Notice>}{data.loading?<Loading/>:<BookingTable rows={rows} onCancel={row=>{setSelected(row);setError('');}}/>}{selected&&<Modal title="Cancel booking?" onClose={()=>setSelected(null)}><p>{selected.className} · {dateLabel(selected.date)}</p>{error&&<Notice error>{error}</Notice>}{permitted?<><p className="muted">Your reserved session credit will be released.</p><Button busy={busy} onClick={cancel}>Cancel Booking</Button></>:<><Notice>The cancellation window has closed. Contact the gym for help.</Notice><ActionLink href="/contact">Contact the gym</ActionLink></>}</Modal>}</MemberShell>;}
export function MembershipPage(){const {user,profile}=useAuth();const data=useRows(user?'payments':null,[where('userId','==',user?.uid||''),orderBy('createdAt','desc'),limit(100)],user?.uid);return <MemberShell><PageHeading title="Your Membership."/><div className="card row spread"><div><p className="eyebrow">Training credits</p><h2 style={{fontSize:32}}>{profile?.sessionsRemaining??0} sessions remaining</h2><p className="muted">{profile?.sessionsReserved??0} reserved for upcoming classes</p></div><ActionLink href="/pricing">Add Session Credits</ActionLink></div><h2 style={{fontSize:28,marginTop:38}}>Payment history</h2>{data.error&&<Notice error>{data.error}</Notice>}{data.loading?<Loading/>:data.rows.length?<div className="table-wrap"><table><thead><tr><th>Date</th><th>Item</th><th>Amount</th><th>Method</th><th>Status</th><th>Delivery</th><th>Receipt</th></tr></thead><tbody>{data.rows.map(p=><tr key={p.id}><td>{dateLabel(p.createdAt)} · {timeLabel(p.createdAt)}</td><td>{p.sessionTitle?p.sessionTitle:p.productName?`${p.productName}${p.size?` · Size ${p.size}`:''} (store)`:'Membership'}</td><td>{money(p.amount)}</td><td>{paymentMethodLabel(p.paymentMethod)}</td><td><span className={`status ${p.status}`}>{p.status}</span></td><td>{p.estimatedDeliveryDate?dateLabel(p.estimatedDeliveryDate):'—'}</td><td>{p.receiptUrl&&<a href={p.receiptUrl} target="_blank" rel="noreferrer">View receipt ↗</a>}</td></tr>)}</tbody></table></div>:<Empty>No payments yet.</Empty>}</MemberShell>;}
export function SettingsPage({embedded=false}:{embedded?:boolean}={}){const {user,profile,logout}=useAuth(),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[avatarUrl,setAvatarUrl]=useState(profile?.avatarUrl||'');async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!user)return;const form=Object.fromEntries(new FormData(e.currentTarget)) as Record<string,string>;setBusy(true);setError('');try{await updateDoc(doc(db,'users',user.uid),{phone:form.phone,address:composeAddress(form),zipCode:form.zipCode,childName:form.childName,childAge:Number(form.childAge),avatarUrl,notificationPreferences:{push:form.push==='on',email:form.emailNotifications==='on',offers:form.offers==='on',reminders:form.reminders==='on',marketing:form.marketing==='on'},updatedAt:serverTimestamp()});setMessage('Profile saved.');}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}async function avatar(file:File|undefined){if(!file||!user)return;if(file.size>=5*1024*1024||!['image/jpeg','image/png','image/webp'].includes(file.type)){setError('Choose a JPG, PNG or WebP smaller than 5 MB.');return;}setBusy(true);setError('');try{const target=ref(storage,`avatars/${user.uid}/profile`);await uploadBytes(target,file,{contentType:file.type});const url=await getDownloadURL(target);setAvatarUrl(url);await updateDoc(doc(db,'users',user.uid),{avatarUrl:url,updatedAt:serverTimestamp()});setMessage('Profile photo updated.');}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}const content=<><PageHeading title="Settings"/>{profile&&<form className="card stack" style={{maxWidth:750}} onSubmit={save}>
  <h3 style={{margin:0}}>Profile photo</h3>
  <div className="row" style={{alignItems:'center',gap:16}}>{avatarUrl&&<img className="avatar" src={avatarUrl} alt="Your profile" style={{width:64,height:64,borderRadius:'50%',objectFit:'cover'}}/>}<label className="field" style={{flex:1}}>Change photo<input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={e=>avatar(e.target.files?.[0])}/></label></div>
  <h3 style={{margin:0}}>Contact & participant</h3>
  <div className="field-grid">{[['childName','Participant name (yourself or child)','text'],['childAge','Participant age','number'],['phone','Phone','tel']].map(([name,label,type])=><label className="field" key={name}>{label}<input name={name} type={type} required defaultValue={profile[name]} min={type==='number'?1:undefined} max={type==='number'?120:undefined}/></label>)}</div>
  <AddressFields defaultStreet={profile.address||''} defaultZipCode={profile.zipCode||''}/>
  <label className="check-field"><input type="checkbox" name="push" defaultChecked={profile.notificationPreferences?.push!==false}/>Push notifications</label><label className="check-field"><input type="checkbox" name="emailNotifications" defaultChecked={profile.notificationPreferences?.email!==false}/>Email notifications</label>{(['offers','reminders','marketing'] as const).map(category=><label className="check-field" key={category}><input type="checkbox" name={category} defaultChecked={profile.notificationPreferences?.[category]!==false}/>{category==='offers'?'Sessions':category[0].toUpperCase()+category.slice(1)}</label>)}{error&&<Notice error>{error}</Notice>}{message&&<Notice>{message}</Notice>}<div className="row"><Button busy={busy}>Save Changes</Button><Button type="button" className="secondary" onClick={async()=>{try{await sendPasswordResetEmail(auth,user!.email!);setMessage('Password reset email sent.');}catch(e){setError(errorMessage(e));}}}>Change Password</Button><Button type="button" className="text" onClick={()=>logout().catch(e=>setError(errorMessage(e)))}>Sign Out</Button></div>
  <label className="field">Email<input value={profile.email||user?.email||''} disabled/></label>
  </form>}</>;return embedded?content:<MemberShell>{content}</MemberShell>;}
export function NotificationsPage(){const {user}=useAuth(),[error,setError]=useState('');const data=useRows(user?'notifications':null,[where('userId','==',user?.uid||''),orderBy('createdAt','desc'),limit(100)],user?.uid);return <MemberShell><PageHeading title="Notifications."/>{(error||data.error)&&<Notice error>{error||data.error}</Notice>}{data.loading?<Loading/>:data.rows.length?<div className="stack">{data.rows.map(n=><article className="card" key={n.id} style={{borderColor:n.isRead?undefined:'var(--red)'}}><h3>{n.title}</h3><p className="muted">{n.body}</p>{!n.isRead&&<Button className="text small" onClick={async()=>{try{await updateDoc(doc(db,'notifications',n.id),{isRead:true});}catch(e){setError(errorMessage(e));}}}>Mark as read</Button>}</article>)}</div>:<Empty>You’re all caught up.</Empty>}</MemberShell>;}
