'use client';
import { FormEvent, useState } from 'react';
import Link from 'next/link';
import { where } from 'firebase/firestore';
import { useRouter } from 'next/navigation';
import { call } from '@/lib/firebase';
import { useDocument, useRows } from '@/lib/hooks';
import { dateLabel, errorMessage, money, timeLabel } from '@/lib/utils';
import { useAuth } from './providers';
import { MemberShell } from './member-pages';
import { ParentPayment } from './parent-payment';
import { ActionLink, Button, Empty, Loading, Notice, PageHeading } from './ui';

export function RequestsPage(){const {user}=useAuth(),data=useRows(user?'sessionRequests':null,[where('userId','==',user?.uid||'')],user?.uid),[busy,setBusy]=useState(''),[error,setError]=useState('');async function cancel(id:string){setBusy(id);setError('');try{await call('cancelSessionRequest',{requestId:id});}catch(e){setError(errorMessage(e));}finally{setBusy('');}}return <MemberShell><PageHeading title="My Requests.">Ask the gym for a private, duo or group session.</PageHeading><ActionLink href="/requests/new">Request a session</ActionLink>{(error||data.error)&&<Notice error>{error||data.error}</Notice>}{data.loading?<Loading/>:data.rows.length?<div className="stack" style={{marginTop:24}}>{[...data.rows].sort((a,b)=>String(b.id).localeCompare(String(a.id))).map(r=><article className="card" key={r.id}><div className="row spread"><h3>{r.trainingType} · {r.seats} seat{r.seats===1?'':'s'}</h3><span className={`status ${r.status}`}>{r.status}</span></div><p className="muted">{r.preferredTimes?.map((t:{date:string;time:string})=>`${t.date} ${t.time}`).join(' · ')}</p>{r.approvedStartAt&&<p>Approved: {dateLabel(r.approvedStartAt)} · {timeLabel(r.approvedStartAt)} · {money(r.approvedPriceCents||0)}</p>}{r.decisionNote&&<p>{r.decisionNote}</p>}<div className="row">{r.status==='approved'&&r.bookingId&&<ActionLink href={`/booking/pay?booking=${encodeURIComponent(r.bookingId)}&request=${encodeURIComponent(r.id)}`}>Pay by {r.payBy?`${dateLabel(r.payBy)} ${timeLabel(r.payBy)}`:'deadline'}</ActionLink>}{['pending','approved'].includes(r.status)&&<Button className="secondary small" busy={busy===r.id} onClick={()=>cancel(r.id)}>Cancel request</Button>}</div></article>)}</div>:<Empty>No requests yet.</Empty>}</MemberShell>;}
export function RequestFormPage(){const router=useRouter(),[type,setType]=useState('private'),[times,setTimes]=useState([{date:'',time:''}]),[busy,setBusy]=useState(false),[error,setError]=useState('');async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=new FormData(e.currentTarget);setBusy(true);setError('');try{await call('createSessionRequest',{trainingType:type,seats:Number(form.get('seats')),preferredTimes:times,note:String(form.get('note')||'')});router.push('/requests');}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}return <MemberShell><PageHeading title="Request a session."/><form className="card stack" style={{maxWidth:700}} onSubmit={submit}><label className="field">Training type<select value={type} onChange={e=>setType(e.target.value)}><option value="private">Private</option><option value="duo">Duo</option><option value="group">Group</option></select></label><label className="field">Seats<input name="seats" type="number" min={1} max={type==='private'?1:type==='duo'?2:10} defaultValue={1} key={type} required/></label><h3>Preferred times (gym local time)</h3>{times.map((t,i)=><div className="field-grid" key={i}><label className="field">Date<input type="date" required value={t.date} onChange={e=>setTimes(old=>old.map((v,j)=>j===i?{...v,date:e.target.value}:v))}/></label><label className="field">Time<input type="time" required value={t.time} onChange={e=>setTimes(old=>old.map((v,j)=>j===i?{...v,time:e.target.value}:v))}/></label></div>)}<div className="row"><Button type="button" className="secondary small" disabled={times.length>=3} onClick={()=>setTimes([...times,{date:'',time:''}])}>Add time</Button><Button type="button" className="text small" disabled={times.length<=1} onClick={()=>setTimes(times.slice(0,-1))}>Remove last</Button></div><label className="field">Note<textarea name="note" maxLength={500}/></label>{error&&<Notice error>{error}</Notice>}<Button busy={busy}>Send request</Button></form></MemberShell>;}
export function RequestPayPage({bookingId,requestId}:{bookingId:string;requestId:string}){const {user}=useAuth(),request=useDocument(user&&requestId?`sessionRequests/${requestId}`:null),booking=useDocument(user&&bookingId?`offerBookings/${bookingId}`:null),[secret,setSecret]=useState(''),[busy,setBusy]=useState(false),[submitted,setSubmitted]=useState(false),[error,setError]=useState('');async function begin(){if(!user)return;setBusy(true);setError('');try{const r=await call<{clientSecret?:string}>('payHeldBooking',{bookingId,requestId});if(r.clientSecret)setSecret(r.clientSecret);else setError('Payment is being processed. Check your bookings.');}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}const valid=user&&request?.userId===user.uid&&request?.bookingId===bookingId&&booking?.userId===user.uid;return <MemberShell><PageHeading title="Pay for your session."/>{!request||!booking?<Loading/>:!valid?<Notice error>Request not found.</Notice>:booking.status==='confirmed'?<><Notice>Your booking is confirmed.</Notice><ActionLink href="/bookings">My Bookings</ActionLink></>:booking.status!=='held'?<Notice>Payment window is closed.</Notice>:<div className="card stack"><p>{request.trainingType} · {request.approvedStartAt&&`${dateLabel(request.approvedStartAt)} ${timeLabel(request.approvedStartAt)}`}</p><h2>{money(booking.amountCents)}</h2>{request.payBy&&<p>Pay by {dateLabel(request.payBy)} · {timeLabel(request.payBy)}</p>}{error&&<Notice error>{error}</Notice>}{submitted&&<Notice>Payment submitted. Waiting for confirmation.</Notice>}{secret?<ParentPayment secret={secret} returnPath={`/booking/pay?booking=${encodeURIComponent(bookingId)}&request=${encodeURIComponent(requestId)}`} onSubmitted={()=>setSubmitted(true)}/>:<Button busy={busy} onClick={begin}>Continue to card payment</Button>}</div>}</MemberShell>;}
