'use client';
import { FormEvent, useMemo, useState } from 'react';
import { Elements, PaymentElement, useElements, useStripe } from '@stripe/react-stripe-js';
import { loadStripe } from '@stripe/stripe-js';
import { useDocument } from '@/lib/hooks';
import { errorMessage } from '@/lib/utils';
import { Button, Notice } from './ui';

function Form({secret,returnPath,onSubmitted,onConfirming,onFailure}:{secret:string;returnPath:string;onSubmitted:()=>void;onConfirming?:()=>void;onFailure?:()=>void}) { const stripe=useStripe(),elements=useElements(),[busy,setBusy]=useState(false),[error,setError]=useState('');const isSettled=(s?:string)=>s==='succeeded'||s==='processing'||s==='requires_capture';async function checkPaid(){try{const r=await stripe?.retrievePaymentIntent(secret);return isSettled(r?.paymentIntent?.status);}catch{return false;}}async function submit(e:FormEvent){e.preventDefault();if(busy||!stripe||!elements)return;setBusy(true);setError('');try{if(await checkPaid()){onSubmitted();return;}onConfirming?.();const result=await stripe.confirmPayment({elements,confirmParams:{return_url:`${location.origin}${returnPath}`},redirect:'if_required'});if(result.error){if(await checkPaid())onSubmitted();else{onFailure?.();setError(result.error.message||'Payment failed.');}}else onSubmitted();}catch(e){if(await checkPaid())onSubmitted();else{onFailure?.();setError(errorMessage(e));}}finally{setBusy(false);}}return <form className="card stack" onSubmit={submit}><PaymentElement/>{error&&<Notice error>{error}</Notice>}<Button busy={busy} disabled={!stripe||!elements}>Pay securely</Button></form>;}
export function ParentPayment({secret,returnPath,onSubmitted,onConfirming,onFailure}:{secret:string;returnPath:string;onSubmitted:()=>void;onConfirming?:()=>void;onFailure?:()=>void}) {const settings=useDocument('gymSettings/config'),key=process.env.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY||settings?.stripePublishableKey||'',stripe=useMemo(()=>/^pk_(test|live)_/.test(key)?loadStripe(key):null,[key]);return stripe?<Elements stripe={stripe} options={{clientSecret:secret,appearance:{theme:'night',variables:{colorPrimary:'#E50914',colorBackground:'#181818'}}}}><Form secret={secret} returnPath={returnPath} onSubmitted={onSubmitted} onConfirming={onConfirming} onFailure={onFailure}/></Elements>:<Notice error>Card payments are unavailable. Contact the gym.</Notice>;}
