'use client';
import { useState } from 'react';
import Link from 'next/link';
import { where } from 'firebase/firestore';
import { QRCodeSVG } from 'qrcode.react';
import { call } from '@/lib/firebase';
import { useDocument, useRows } from '@/lib/hooks';
import { asDate, dateLabel, errorMessage, money, timeLabel } from '@/lib/utils';
import { useAuth } from './providers';
import { MemberShell } from './member-pages';
import { ActionLink, Button, Empty, Loading, Notice, PageHeading } from './ui';

function OfferBookingCard({b,tab,onCancel,busy,preview,onPreview}:{b:any;tab:string;onCancel:(id:string)=>void;busy:string;preview?:{allowed:boolean;message?:string};onPreview:(id:string)=>void}){const o=useDocument(b.occurrenceId?`offerOccurrences/${b.occurrenceId}`:null);return <article className="card"><div className="row spread"><h3>{o?.title||'Session'}</h3><span className={`status ${b.status}`}>{b.status.replace('_',' ')}</span></div><p>{o&&`${dateLabel(o.startAt)} · ${timeLabel(o.startAt)} · `}{b.seats} seat{b.seats===1?'':'s'} · {money(b.amountCents||0)}</p><p className="muted">{b.participants?.map((p:{name:string})=>p.name).join(' · ')}</p><div className="row">{b.status==='confirmed'&&<ActionLink href={`/offer-bookings/pass?id=${encodeURIComponent(b.id)}`}>Check-in pass</ActionLink>}{b.status==='confirmed'&&o&&+asDate(o.startAt)>Date.now()&&<>{preview?preview.allowed?<Button className="secondary small" busy={busy===b.id} onClick={()=>onCancel(b.id)}>Confirm cancellation</Button>:<Notice>{preview.message||'Cancellation is unavailable.'}</Notice>:<Button className="secondary small" onClick={()=>onPreview(b.id)}>Cancel booking</Button>}</>}{b.status==='held'&&<span className="muted">Payment in progress</span>}</div></article>;}
export function OfferBookingsSection({tab}:{tab:string}){const {user}=useAuth(),data=useRows(user?'offerBookings':null,[where('userId','==',user?.uid||'')],user?.uid),publicOcc=useRows('offerOccurrences',[where('visibility','==','public'),where('offerStatus','==','published')]),privateOcc=useRows(user?'offerOccurrences':null,[where('ownerUserId','==',user?.uid||'')],user?.uid),[busy,setBusy]=useState(''),[error,setError]=useState(''),[preview,setPreview]=useState<Record<string,{allowed:boolean;message?:string}>>({});const all=[...publicOcc.rows,...privateOcc.rows],rows=data.rows.filter(b=>{if(tab==='cancelled')return ['cancelled','expired','refunded','refund_pending'].includes(b.status);if(!['held','confirmed'].includes(b.status))return false;const o=all.find(x=>x.id===b.occurrenceId);return !!o&&((tab==='upcoming')===(+asDate(o.startAt)>Date.now()));});async function cancel(id:string){setBusy(id);setError('');try{await call('cancelOfferBooking',{bookingId:id});}catch(e){setError(errorMessage(e));}finally{setBusy('');}}async function check(id:string){try{const result=await call<{allowed:boolean;message?:string}>('previewOfferCancellation',{bookingId:id});setPreview(old=>({...old,[id]:result}));}catch(e){setError(errorMessage(e));}}return <section style={{marginTop:36}}><h2>Session bookings</h2>{(error||data.error||publicOcc.error||privateOcc.error)&&<Notice error>{error||data.error||publicOcc.error||privateOcc.error}</Notice>}{data.loading||publicOcc.loading||privateOcc.loading?<Loading/>:rows.length?<div className="stack">{rows.map(b=><OfferBookingCard key={b.id} b={b} tab={tab} busy={busy} preview={preview[b.id]} onPreview={check} onCancel={cancel}/>)}</div>:<Empty>No session bookings in this category.</Empty>}</section>;}
export function CheckInPassPage({id}:{id:string}){const {user}=useAuth(),booking=useDocument(user?`offerBookings/${id}`:null),occ=useDocument(booking?.occurrenceId?`offerOccurrences/${booking.occurrenceId}`:null),[now]=useState(()=>Date.now());const valid=booking&&user&&booking.userId===user.uid,windowOpen=occ&&+asDate(occ.startAt)-24*3600000<=now&&now<+asDate(occ.endAt);return <MemberShell><PageHeading title="Check-in pass."/>{!booking||!occ?<Loading/>:!valid?<Notice error>Pass not found.</Notice>:<div className="card stack" style={{maxWidth:500}}><h2>{occ.title}</h2><p>{dateLabel(occ.startAt)} · {timeLabel(occ.startAt)}</p><p>{booking.participants?.map((p:{name:string})=>p.name).join(' · ')}</p>{booking.checkedInAt?<Notice>Checked in at {timeLabel(booking.checkedInAt)}.</Notice>:booking.status!=='confirmed'?<Notice>This booking is not confirmed.</Notice>:!windowOpen?<Notice>The pass appears from 24 hours before the session until it ends.</Notice>:booking.checkInCode?<><div className="parent-qr" role="img" aria-label="Check-in QR code"><QRCodeSVG value={`jbb://checkin/${id}/${booking.checkInCode}`} size={240} marginSize={2}/></div><p className="muted">Show this QR code to staff at check-in.</p></>:<Notice>Check-in code is not available yet.</Notice>}<ActionLink href="/bookings">My Bookings</ActionLink></div>}</MemberShell>;}
