'use client';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { where } from 'firebase/firestore';
import { useDocument, useRows } from '@/lib/hooks';
import { Row } from '@/lib/types';
import { money } from '@/lib/utils';
import { soldOut, stockFor } from '@/lib/parent-data';
import { ActionLink, Button, Loading, Notice, Empty, PageHeading } from './ui';
import { useAuth } from './providers';
import { AuthModal } from './auth-modal';
export function Store(){const {rows,loading,error}=useRows('products',[where('isActive','==',true)]);if(loading)return <Loading/>;if(error)return <Notice error>{error}</Notice>;if(!rows.length)return <Empty>Products will appear here when available.</Empty>;return <div className="plan-grid">{[...rows].sort((a,b)=>(a.sortOrder??0)-(b.sortOrder??0)).map(p=><article className="plan" key={p.id}>{p.imageUrl&&<img src={p.imageUrl} alt={p.name} className="parent-cover"/>}<p className="eyebrow">{p.category||'Gym shop'}</p><h3>{p.name}</h3><p>{p.discountActive&&p.discountPercent>0?money(Math.round(p.price*(1-p.discountPercent/100))):p.priceLabel||money(p.price)}</p><p className="muted">{soldOut(p)?'Sold out':'Pickup at the gym'}</p><ActionLink href={`/store/product?id=${encodeURIComponent(p.id)}`}>View product</ActionLink></article>)}</div>;}
export function StorePage(){return <div className="container page-wrap"><PageHeading eyebrow="Fight-night shop" title="Wear your corner.">Order online. Pick up at the gym.</PageHeading><Store/></div>;}
export function ProductDetailPage({id}:{id:string}){const p=useDocument(`products/${id}`),router=useRouter(),{user,loading:authLoading}=useAuth(),[size,setSize]=useState(''),[image,setImage]=useState(0),[showAuth,setShowAuth]=useState(false);const checkout=()=>router.push(`/checkout?product=${encodeURIComponent(id)}${size?`&size=${encodeURIComponent(size)}`:''}`);if(!p)return <div className="container page-wrap"><Loading/></div>;if(!p.isActive)return <div className="container page-wrap"><Empty>Product unavailable.</Empty></div>;const sizes:string[]=p.sizes||[],images:string[]=p.imageUrls?.length?p.imageUrls:p.imageUrl?[p.imageUrl]:[];const sale=p.discountActive&&p.discountPercent>0?Math.round(p.price*(1-p.discountPercent/100)):p.price;return <div className="container page-wrap"><div className="product-detail">{images.length>0&&<div><img className="parent-detail-cover" src={images[image]} alt={p.name}/>{images.length>1&&<div className="row">{images.map((src,i)=><button className={`product-thumb ${image===i?'active':''}`} key={src} onClick={()=>setImage(i)}><img src={src} alt={`${p.name} view ${i+1}`}/></button>)}</div>}</div>}<div className="card stack"><p className="eyebrow">{p.category||'Fight-night shop'}</p><h1>{p.name}</h1><p>{p.description}</p><h2>{money(sale)}{sale!==p.price&&<span className="price-was">{money(p.price)}</span>}</h2>{sizes.length>0&&<><h3>Choose a size</h3><div className="size-picker">{sizes.map(s=><button key={s} className={`button small ${size===s?'':'secondary'}`} disabled={stockFor(p,s)===0} onClick={()=>setSize(s)}>{s}{stockFor(p,s)===0?' · Sold out':''}</button>)}</div></>}{p.stock!=null&&<p className="muted">{sizes.length?size?`${stockFor(p,size)} available in ${size}`:'Select an available size':`${stockFor(p)} available`}</p>}<p className="muted">Pickup at the gym only. Stock is held for 10 minutes during checkout.</p><Button disabled={authLoading||soldOut(p)||(sizes.length>0&&!size)} onClick={()=>user?checkout():setShowAuth(true)}>Checkout</Button></div></div>{showAuth&&<AuthModal onClose={()=>setShowAuth(false)} onSignedIn={()=>{setShowAuth(false);checkout();}}/>}</div>;}
